# Generated by Django 4.0.3 on 2022-03-21 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ac_app', '0004_accaunt_created_at_accaunt_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accaunt',
            name='num',
        ),
    ]
