# Generated by Django 4.0.3 on 2022-03-25 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ac_app', '0005_remove_accaunt_num'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Accaunt',
            new_name='Account',
        ),
    ]
